### ISSUE TITLE
Docker wont build

### ISSUE THREAD

**Issue by GeeraertHerber** [Yimura/node-ytdl-gui#15]
So I pulled from docker with your provided command. 
Then I would run the second command but this gives a error 

This is the error: `standard_init_linux.go:211: exec user process caused "exec format error"`

I've tried to fix it by manipulating the command but nothing seems to work. 

Can you help?

**Comment by Yimura** [comment]
Ok let me try to reproduce this problem, there might be a problem with the setup commands.

**Comment by Yimura** [comment]
On what operating system are you building this?

**Comment by GeeraertHerber** [comment]
I'm building this on RPi OS on a RPi 4 4GB

**Comment by Yimura** [comment]
Are you building the image from source or pulling from docker hub?

Can you post which commands you're using?

**Comment by GeeraertHerber** [comment]
```
docker pull yimura/ytdl
docker run --init --name ytdl -p 8080:8080 yimura/ytdl
```

**Comment by Yimura** [comment]
Huh strange, this might be a problem with running the container on ARM, I might have to look into building seperate ARM images.

**Comment by GeeraertHerber** [comment]
With that building from the pulled source gives also a error

**Comment by Yimura** [comment]
Try using the following command to build the source code to a docker image on your Raspberry Pi.
It will build a local docker container and run it directly after.

```
docker build --no-cache --tag ytdl:test_build . && docker run --init --name ytdl -p 8080:8080 -d ytdl:test_build
```

I don't have an ARM device available to build one right now.

**Comment by Yimura** [comment]
I build an ARM image for you, it should work if your install of docker works.

```
docker pull yimura/ytdl:arm
docker run --init --name ytdl -p 8080:8080 yimura/ytdl:arm
```

**Comment by GeeraertHerber** [comment]
Thank you, It works like a charm.
