### ISSUE TITLE
Add allowlist/denylist support

### ISSUE THREAD

**Issue by GeopJr** [Yimura/node-ytdl-gui#2]
It would be nice if we could allow only some certain sites or disallow others.

Like
```
allowList: ["youtube.com", "soundcloud.com"]
```
And
```
denyList: ["vimeo.com"]
```

(allowList gets priority over denyList)

**Comment by Yimura** [comment]
Sounds good, I'll look how it'll be best to implement this.

**Comment by Yimura** [comment]
After reviewing this it seemed idiotic to have allowList and denyList exist together.

I would rather have only one of both exist and have an DENY ALL or ALLOW ALL rule and then use the above lists to make an exception.

```
// Allow all by default
denyList: ['vimeo.com']
```
or
```
// Deny all by default but make an exception
allowList: ['youtube.com', 'youtu.be']
```

**Comment by GeopJr** [comment]
Agreed.
